version: "3.8"
services:
  app:
    depends_on:
      - db
    build: ./funkydrive-backend
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    volumes:
      - .m2:/root/.m2
      - ./funkydrive-backend:/app
    stdin_open: true
    tty: true

  db:
    container_name: postgres_drive
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./DataBase/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./DataBase/postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}

  adminer:
    container_name: adminer_quizz
    image: adminer:latest
    restart: always
    ports:
      - "5050:8080"
    env_file:
      - .env
    depends_on:
      - db
